Repository gruntsoftware/android, pull requests merged in 2025-08, with the labels that each got.

#115 🚀[Release v4.7.0] Merge into Main
  app/CMakeLists.txt
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/brainwallet/BrainwalletApp.kt
  app/src/main/java/com/brainwallet/di/Module.kt
  app/src/main/java/com/brainwallet/navigation/LegacyNavigation.kt
  app/src/main/java/com/brainwallet/ui/screens/buylitecoin/BuyLitecoinScreen.kt
  app/src/main/java/com/brainwallet/ui/screens/home/receive/ReceiveDialog.kt
  app/src/main/java/com/brainwallet/ui/screens/welcome/WelcomeScreen.kt
  app/src/main/java/com/brainwallet/ui/screens/yourseedproveit/YourSeedProveItScreen.kt
  app/src/main/res/drawable-hdpi/brainwallet_logotype_white.png
  app/src/main/res/drawable-mdpi/brainwallet_logotype_white.png
  app/src/main/res/drawable-xhdpi/brainwallet_logotype_white.png
  app/src/main/res/drawable-xxhdpi/brainwallet_logotype_white.png
  app/src/main/res/drawable-xxxhdpi/brainwallet_logotype_white.png
  app/src/main/res/drawable/brainwallet_logotype_black.png
  app/src/main/res/drawable/brainwallet_logotype_color.png
  app/src/main/res/drawable/brainwallet_logotype_white.png
  app/src/test/java/com/brainwallet/tools/util/BRConstantsTest.kt
  gradle/libs.versions.toml
Labels: release

#126 Fix(#227): Crash when launching MoonPay Widget
  app/src/main/java/com/brainwallet/navigation/LegacyNavigation.kt
  app/src/main/java/com/brainwallet/navigation/MoonPayWidgeLauncher.kt
  app/src/main/java/com/brainwallet/ui/screens/buylitecoin/BuyLitecoinScreen.kt
  app/src/main/java/com/brainwallet/ui/screens/home/receive/ReceiveDialog.kt
Labels: bug

#122 feat(#138): Update Unlock Screen UI
  app/build.gradle.kts
  app/src/main/java/com/brainwallet/navigation/UiEffect.kt
  app/src/main/java/com/brainwallet/tools/qrcode/QRUtils.java
  app/src/main/java/com/brainwallet/ui/composable/BrainWalletLogo.kt
  app/src/main/java/com/brainwallet/ui/composable/DarkModeToggleButton.kt
  app/src/main/java/com/brainwallet/ui/composable/Foundation.kt
  app/src/main/java/com/brainwallet/ui/composable/PasscodeIndicator.kt
  app/src/main/java/com/brainwallet/ui/screens/home/receive/ReceiveDialog.kt
  app/src/main/java/com/brainwallet/ui/screens/home/receive/ReceiveDialogFragment.kt
  app/src/main/java/com/brainwallet/ui/screens/unlock/UnLockEvent.kt
  app/src/main/java/com/brainwallet/ui/screens/unlock/UnLockScreen.kt
  app/src/main/java/com/brainwallet/ui/screens/unlock/UnLockState.kt
  app/src/main/java/com/brainwallet/ui/screens/unlock/UnLockViewModel.kt
  app/src/main/java/com/brainwallet/ui/screens/unlock/components/UnLockScreenBody.kt
  app/src/main/java/com/brainwallet/ui/screens/unlock/components/UnLockScreenFooter.kt
  app/src/main/java/com/brainwallet/ui/screens/unlock/components/UnLockScreenHeader.kt
  app/src/main/java/com/brainwallet/ui/theme/Theme.kt
  app/src/main/java/com/brainwallet/util/CurrencyDataGetter.kt
  app/src/main/java/com/brainwallet/util/VersionCodeProvider.kt
  app/src/main/res/drawable-hdpi/brainwallet_logotype_color.webp
  app/src/main/res/drawable-ldpi/brainwallet_logotype_color.webp
  app/src/main/res/drawable-mdpi/brainwallet_logotype_color.webp
  app/src/main/res/drawable-xhdpi/brainwallet_logotype_color.webp
  app/src/main/res/drawable-xxhdpi/brainwallet_logotype_color.webp
  app/src/main/res/drawable-xxxhdpi/brainwallet_logotype_color.webp
  app/src/main/res/drawable/ic_clickable_qr.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/brainwallet/ui/screens/unlock/UnLockViewModelTest.kt
  app/src/test/java/com/brainwallet/util/CurrencyDataGetterTest.kt
  app/src/test/java/com/brainwallet/util/MainDispatcherRule.kt
  app/src/test/java/com/brainwallet/util/VersionCodeProviderTest.kt
  gradle/libs.versions.toml
Labels: enhancement

#132 feat(#234): Implement language-specific Firebase messaging topics
  app/src/main/java/com/brainwallet/BrainwalletApp.kt
  app/src/main/java/com/brainwallet/data/repository/MessagingTopicRepository.kt
  app/src/main/java/com/brainwallet/data/source/MessagingTopicDataSource.kt
  app/src/main/java/com/brainwallet/domain/LanguageSwitcherUseCase.kt
  app/src/main/java/com/brainwallet/domain/MessagingTopicUseCase.kt
  app/src/main/java/com/brainwallet/presenter/language/ChangeLanguageBottomSheet.kt
  app/src/main/java/com/brainwallet/ui/screens/home/SettingsViewModel.kt
  app/src/test/java/com/brainwallet/data/repository/MessagingTopicRepositoryTest.kt
  app/src/test/java/com/brainwallet/data/source/MessagingTopicDataSourceTest.kt
  app/src/test/java/com/brainwallet/domain/LanguageSwitcherUseCaseTest.kt
  app/src/test/java/com/brainwallet/domain/MessagingTopicUseCaseTest.kt
Labels: enhancement, android
