Repository gruntsoftware/android, pull requests merged in 2025-02, with the labels that each got.

#8 [screengrab] need grant post notification
  app/build.gradle.kts
  app/src/androidTest/kotlin/flow/RecoverWalletScreenGrabsTest.kt
Labels: techdebt

#12 Techdebt/add language tracks: added hindi and Arabic
  app/src/main/java/com/brainwallet/data/model/IntroLanguageResource.kt
  app/src/main/java/com/brainwallet/data/model/Language.kt
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/change_language_bottom_sheet.xml
  app/src/main/res/layout/language_list.xml
  app/src/main/res/raw/hindi.mp3
  app/src/main/res/raw/simplifiedchinese.mp3
  app/src/test/java/com/brainwallet/tools/util/LocaleHelperTest.kt
  fast_follow_asset_pack_01/src/main/assets/audio/arabic.mp3
  fast_follow_asset_pack_01/src/main/assets/audio/hindi.mp3
  fast_follow_asset_pack_01/src/main/assets/audio/simplifiedchinese.mp3
Labels: enhancement, techdebt

#16 Removed the random greeting
  app/src/main/java/com/brainwallet/presenter/activities/BreadActivity.java
  app/src/main/java/com/brainwallet/presenter/activities/InputWordsActivity.kt
  app/src/main/java/com/brainwallet/presenter/activities/SetPinActivity.java
  app/src/main/java/com/brainwallet/presenter/fragments/FragmentGreetings.java
  app/src/main/java/com/brainwallet/tools/animation/BRAnimator.java
  app/src/main/java/com/brainwallet/tools/manager/BRSharedPrefs.java
  app/src/main/res/layout/fragment_greetings.xml
Labels: enhancement

#17 techdebt: clean up host
  app/src/main/java/com/brainwallet/BrainwalletApp.java
Labels: techdebt

#20 Set Pin limit
  app/src/main/java/com/brainwallet/presenter/activities/LoginActivity.java
  app/src/main/java/com/brainwallet/presenter/activities/ReEnterPinActivity.java
  app/src/main/java/com/brainwallet/presenter/activities/SetPinActivity.java
  app/src/main/java/com/brainwallet/presenter/activities/UpdatePinActivity.java
  app/src/main/java/com/brainwallet/presenter/fragments/FragmentPin.java
  app/src/main/java/com/brainwallet/tools/security/AuthManager.java
  app/src/main/res/layout/activity_pin.xml
  app/src/main/res/layout/activity_pin_template.xml
  app/src/main/res/layout/activity_security_center.xml
  app/src/main/res/layout/fragment_bread_pin.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/security_center_list_item.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#21 Move layout of lockscreen
  app/src/main/java/com/brainwallet/presenter/activities/LoginActivity.java
  app/src/main/java/com/brainwallet/presenter/activities/ReEnterPinActivity.java
  app/src/main/java/com/brainwallet/presenter/activities/SetPinActivity.java
  app/src/main/java/com/brainwallet/presenter/activities/UpdatePinActivity.java
  app/src/main/java/com/brainwallet/presenter/fragments/FragmentPin.java
  app/src/main/java/com/brainwallet/tools/security/AuthManager.java
  app/src/main/res/layout/activity_pin.xml
  app/src/main/res/layout/activity_pin_template.xml
  app/src/main/res/layout/activity_security_center.xml
  app/src/main/res/layout/fragment_bread_pin.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/security_center_list_item.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#22 Fix/re design lockscreen issue 63
  app/src/main/java/com/brainwallet/presenter/activities/LoginActivity.java
  app/src/main/java/com/brainwallet/presenter/activities/UpdatePinActivity.java
  app/src/main/res/layout/activity_pin.xml
Labels: bug

#23 Techdebt/simplify theme issue 64
  app/src/main/java/com/brainwallet/data/model/AppSetting.kt
  app/src/main/java/com/brainwallet/data/repository/SettingRepository.kt
  app/src/main/java/com/brainwallet/di/Module.kt
  app/src/main/java/com/brainwallet/navigation/LegacyNavigation.kt
  app/src/main/java/com/brainwallet/presenter/activities/LoginActivity.java
  app/src/main/java/com/brainwallet/tools/security/PostAuth.java
  app/src/main/java/com/brainwallet/ui/BrainwalletActivity.kt
  app/src/main/java/com/brainwallet/ui/composable/CircleButton.kt
  app/src/main/java/com/brainwallet/ui/composable/Foundation.kt
  app/src/main/java/com/brainwallet/ui/composable/LargeButton.kt
  app/src/main/java/com/brainwallet/ui/composable/PasscodeKeypad.kt
  app/src/main/java/com/brainwallet/ui/composable/PinDotItem.kt
  app/src/main/java/com/brainwallet/ui/composable/SeedWordItem.kt
  app/src/main/java/com/brainwallet/ui/screens/inputwords/InputWordsScreen.kt
  app/src/main/java/com/brainwallet/ui/screens/inputwords/InputWordsViewModel.kt
  app/src/main/java/com/brainwallet/ui/screens/ready/ReadyScreen.kt
  app/src/main/java/com/brainwallet/ui/screens/setpasscode/SetPasscodeScreen.kt
  app/src/main/java/com/brainwallet/ui/screens/setpasscode/SetPasscodeState.kt
  app/src/main/java/com/brainwallet/ui/screens/setpasscode/SetPasscodeViewModel.kt
  app/src/main/java/com/brainwallet/ui/screens/unlock/UnLockScreen.kt
  app/src/main/java/com/brainwallet/ui/screens/unlock/UnLockState.kt
  app/src/main/java/com/brainwallet/ui/screens/unlock/UnLockViewModel.kt
  app/src/main/java/com/brainwallet/ui/screens/welcome/WelcomeEvent.kt
  app/src/main/java/com/brainwallet/ui/screens/welcome/WelcomeScreen.kt
  app/src/main/java/com/brainwallet/ui/screens/welcome/WelcomeState.kt
  app/src/main/java/com/brainwallet/ui/screens/welcome/WelcomeViewModel.kt
  app/src/main/java/com/brainwallet/ui/screens/yourseedproveit/YourSeedProveItScreen.kt
  app/src/main/java/com/brainwallet/ui/screens/yourseedwords/YourSeedWordsScreen.kt
  app/src/main/java/com/brainwallet/ui/theme/Color.kt
  app/src/main/java/com/brainwallet/ui/theme/Theme.kt
  app/src/main/java/com/brainwallet/ui/theme/Type.kt
  app/src/main/java/com/brainwallet/util/EventBus.kt
  app/src/main/res/drawable/ic_dark_mode.xml
  app/src/main/res/drawable/ic_light_mode.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#25 Pre-Release: v4.2.4: Migration of themes
  app/build.gradle.kts
Labels: release

#28 Slight refactor of layout
  app/src/main/java/com/brainwallet/ui/screens/unlock/UnLockScreen.kt
Labels: bug, techdebt

#29 🚀 [Release - Debug] version and code bump
  app/build.gradle.kts
  app/src/main/java/com/brainwallet/data/model/IntroLanguageResource.kt
Labels: release

#38 🚀[Release v4.30] Merge into Develop
  app/build.gradle.kts
  app/src/main/java/com/brainwallet/presenter/activities/settings/DisplayCurrencyActivity.java
  app/src/main/java/com/brainwallet/tools/sqlite/BRSQLiteHelper.java
  app/src/main/java/com/brainwallet/tools/sqlite/CurrencyDataSource.java
  app/src/main/java/com/brainwallet/ui/composable/bottomsheet/FiatSelectorBottomSheet.kt
  app/src/test/java/com/brainwallet/currency/CurrencyTests.kt
  app/src/test/java/com/brainwallet/tools/database/DatabaseTests.kt
Labels: release
